name: on-push
run-name: on push to main

on:
  push:
    branches:
      - main

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-site:
    uses: ./.github/workflows/build-site.yaml
